version: '3.8'
services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: lab10-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - lab10_net

networks:
  lab10_net:
    driver: bridge
