services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: lab8-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data

volumes:
  mosquitto_data:
